name: Deploy to cPanel

on:
  push:
    branches:
      - deployment-branch  # Set this to your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Match your cPanel PHP version
          extensions: mbstring, xml, ctype, iconv, intl

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.prod_FTP_USERNAME }}
          password: ${{ secrets.prod_FTP_PASSWORD }}
          # The path on your cPanel server (e.g., public_html/my-app)
          server-dir: /
          # Optional: exclude git or config files
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**